version: "3.9"
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    environment:
      - MYSQL_DATABASE=road
      - MYSQL_ROOT_PASSWORD=secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret